# This is a basic workflow to help you get started with Actions

name: tagging and release 

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      create_new_tag:
        description: create_new_tag? 
        required: true
        default: 'false'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          submodules: recursive
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Form tag name
        id: tag_id
        run: |
        
          git config user.name github-actions@github.com
          git config user.email github-actions
          git config --global http.postBuffer 1048576000
          
          git fetch --tags
          
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "latest tag"
          echo $latest_tag
          
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo ${{ env.RELEASE_VERSION }}

          version=`echo $latest_tag| cut -d. -f1`
          major=`echo $latest_tag | cut -d. -f2`
          minor=`echo $latest_tag | cut -d. -f3`
          branch=${{ steps.extract_branch.outputs.branch }}
          
          if [[ $branch == 'main' &&  "${{ github.event.inputs.create_new_tag }}" == "true" ]] ; then
            echo $branch 
            echo "true"
            version=${version#"v"}
            version=`expr $version + 1`
            version=v${version}
            echo $version
            
          elif [ $branch == 'main' ]; then
            echo $branch 
            version=${version#"v"}
            major=`expr $major + 1`

          elif [ $branch == 'develop' ]; then
              echo $branch
              if [ -z "$minor" ]; then
                 minor=0
              else
                  minor=`expr $minor + 1`
              fi


          fi
          
          tag_name=$version.$major.$minor
          echo "tag"
          echo $tag_name
          

          echo ::set-output name=tag_id::$tag_name

   
          
      - name: Release snapshot
        id: release-snapshot
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_id.outputs.tag_id }}
          release_name: ${{ steps.tag_id.outputs.tag_id }}
          draft: false
          prerelease: false
          
      
